GET http://localhost:4000/api/tiposVehiculos

###

GET http://localhost:4000/api/tiposVehiculos/1

###

POST http://localhost:4000/api/tiposVehiculos
Content-Type: application/json

{
    "nombre": "Robusto",
    "descripcion": "Es robuesto pues"
}

###

PUT http://localhost:4000/api/tiposVehiculos/1
Content-Type: application/json

{
    "nombre": "Deportivo",
    "descripcion": "Es deportivo gg"
}

###

DELETE http://localhost:4000/api/tiposVehiculos/1